### ISSUE TITLE
Add support for Julia

### ISSUE THREAD

**Issue by mdpiper** [csdms/bmi#108]
The BMI should support Julia by including a language specification, a sample implementation, and documentation.

**Comment by mdpiper** [comment]
This is a task in the OpenEarthscape award.

**Comment by jeromaerts** [comment]
@RolfHut Yes they made a Julia-BMI implementation: https://github.com/Deltares/BasicModelInterface.jl . The Julia-BMI implementation of their hydrological model can be found here: https://github.com/Deltares/Wflow.jl/blob/master/src/bmi.jl .

**Comment by visr** [comment]
Thanks for sharing @jeromaerts. And for completeness here is an example of how a Julia BMI interface can be applied on top of a shared library: https://github.com/Deltares/ModflowInterface.jl

**Comment by mdpiper** [comment]
Fixed with #120.
