### ISSUE TITLE
CI failure due to deprecation warning on docs

### ISSUE THREAD

**Issue by PhilMiller** [csdms/bmi#124]
> ` WARNING: The pre-Sphinx 1.0 'intersphinx_mapping' format is deprecated and will be removed in Sphinx 8. Update to the current format as described in the documentation. Hint: "intersphinx_mapping = {'<name>': ('https://docs.python.org/', None)}".https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#confval-intersphinx_mapping`

_Originally posted by @PhilMiller in https://github.com/csdms/bmi/issues/123#issuecomment-1591996725_

**Comment by mdpiper** [comment]
Fixed with #122.

**Comment by PhilMiller** [comment]
Oh, I see. Thank you.

Should fresh PRs (e.g. #123) generally be targeting `stable` rather than `develop`? Or is there some process by which those changes get merged over? I didn't see anything about preferred branch or such in the contributing guidelines.

**Comment by mdpiper** [comment]
@PhilMiller I've been adding minor changes to `stable`, then manually merging `stable` into `develop`. Structural changes, or changes to the BMI itself, go to `develop`. No docs on this; we're pretty low-volume (interfaces don't like to change!), but @mcflugen or I can communicate with people on issues or PRs.

**Comment by PhilMiller** [comment]
Ok. I've rebased #123 on `stable` and re-targeted the PR there. I'll leave the merge to `develop` to you
