### ISSUE TITLE
Abstract class in C++ version

### ISSUE THREAD

**Issue by MartineDeVos** [csdms/bmi#16]
eWatercycle II: One would expect a C++ abstract base class as an interface, but instead the C interface is used. We would like to see this extended.

**Comment by mdpiper** [comment]
@MartineDeVos I've revised the [C++ BMI bindings](https://github.com/csdms/bmi-cxx), supplying an abstract base class, `Bmi`, in the header file [bmi.hxx](https://github.com/csdms/bmi-cxx/blob/master/bmi.hxx).

Note that I'm somewhat new to C++, so any feedback you have would be appreciated.

**Comment by mdpiper** [comment]
Fixed. See the current C++ specification: https://github.com/csdms/bmi-cxx/blob/master/bmi.hxx.
