### ISSUE TITLE
preprocessor conditionals missing in C++ header

### ISSUE THREAD

**Issue by goord** [csdms/bmi#31]
To prevent multiple definitions of the same symbols during the linking stage, it is standard practice to wrap every C/C++ header file into its own preprocessor conditionals. For the bmi.cxx this means we have to use something like
```
#ifndef BMI_HXX_INCLUDED
#define BMI_HXX_INCLUDED
...contents of current bmi.hxx...
#endif
```

**Comment by mdpiper** [comment]
@goord I added a header guard to [bmi.hxx](https://github.com/csdms/bmi-cxx/blob/master/bmi.hxx), which defines the C++ BMI bindings. To check that it works, I included this file in the examples and tests in https://github.com/csdms/bmi-example-cxx like so:
```
#include "heat.hxx"
#include <bmi.hxx>
#include "bmi_heat.hxx"
``` 
Without the guard, the contents of `bmi.hxx` would be included twice.

**Comment by mdpiper** [comment]
@goord Also updated the C [bindings](https://github.com/csdms/bmi-c/blob/master/bmi.h) and [example](https://github.com/csdms/bmi-example-c), as well.

**Comment by goord** [comment]
Great, closing the issue.
