### ISSUE TITLE
Questions related to making the terrainbento BMI

### ISSUE THREAD

**Issue by kbarnhart** [csdms/bmi#44]
@mdpiper @mcflugen 

I'm  working on the PyMT compatible BMI for [terrainbento](https://github.com/TerrainBento/terrainbento) ([PR 137 in that repo](https://github.com/TerrainBento/terrainbento/pull/137)). I'm basing it off of 

- conversations with @mcflugen 
- the bmi.py file in this repo (based on recommendations from @mdpiper )

I have a couple of questions... 

1) Is it reasonable to expect that eventually this repository will be packaged and distributed so that I can include it as a dependency and ensure I am always using an up-to-date `bmi.py` via something like `from bmi import BMI` (where `bmi` is the installed package)?
2) Based on conversations with @mcflugen I was under the impression that it was necessary to expose information about the input parameters (as opposed to state variables) to each model (as well as default values, reasonable ranges, etc). But I don't see anything like this in `bmi.py`. Can I get a recommendation?
3) If I create a bmi that inherits from `bmi.py` is it _by definition_ compatible with PyMT. Or are there additional things I should expect to do? 
    - If the answer involved additional things, should I have been able to find this in documentation?

**Comment by mdpiper** [comment]
@kbarnhart I think we've addressed the questions you've raised.

1. The [csdms/bmi-python](https://github.com/csdms/bmi-python) repo is used to create the `bmipy` package, which can be installed from pip, conda, or source. The Python BMI can be imported from this package with `from bmipy import Bmi`. The package is versioned, so you'll know which version of BMI you're using.
1. Model parameters only need to be described in pymt, not in the model BMI.
1. The `bmipy` package isn't used yet in our workflow for building pymt components, but it will be. I think it's safe to state that using `bmipy` will ensure that your model BMI is pymt-compatible.

**Comment by mdpiper** [comment]
The three questions posed by @kbarnhart have been addressed. Closing.
