### ISSUE TITLE
Grid ID

### ISSUE THREAD

**Issue by kbarnhart** [csdms/bmi#45]
@mdpiper and @mcflugen another question motivated by making the [terrainbento bmi](https://github.com/TerrainBento/terrainbento/pull/137):

I see that there are a number of functions in the `bmi.py` file that indicate needing a grid identifier. The best/most relevant part of the documentation that I can find was [this section on Variables[sic?] Grids](https://bmi-spec.readthedocs.io/en/latest/bmi.var_funcs.html?highlight=id#variables-grids). It does not give me enough information.

Reading between the lines I think that what this is saying is that I'm allowed to define multiple grids within my model. If I do this, I need to give them unique IDs that are integers and allow them to be accessed in this way. Correct?

**Comment by mcflugen** [comment]
Correct. A BMI implementation may have multiple grids and each grid must have a unique identifier (as an integer).

Note that variables may be defined on different grid elements of a single grid. For example, you are allowed to have variables defined on a grid's nodes and edges. In such a case, your component would still have a single grid.

Another note: BMI and *landlab* use a different nomenclature for grid elements.

landlab | BMI
--- | ---
node | node
link | edge
patch | patch
corner | node
face | edge
cell | patch

BMI doesn't have the concept of a dual grid like landlab does so the dual grid elements of landlab are a separate grid with their own nodes, edges, and patches.

**Comment by kbarnhart** [comment]
@mcflugen very helpful -- thank you! Closing.

**Comment by mcflugen** [comment]
@kbarnhart Ooops. I just noticed I made a mistake in the above. *landlab* patches are BMI *faces* (not *patches*). I've updated the comment to reflect the correct names.
