### ISSUE TITLE
SIDL reminders in generated files?

### ISSUE THREAD

**Issue by teuben** [csdms/bmi#68]
If certain files (e.g. bmi-c/bmi.h) are generated via the bmi.sidl and some procedure, this fact should be a comment in those files, as to yet again remind authors of the proper workflow.

https://github.com/openjournals/joss-reviews/issues/2317

**Comment by mdpiper** [comment]
@teuben Currently, the language files (like bmi-c/bmi.h) are created manually. However, it's a really good idea to generate them programmatically. @mcflugen and I are scoping out the work for this now.

**Comment by teuben** [comment]
given #71 this can be closed I guess.

**Comment by mdpiper** [comment]
Thanks, @teuben!
