### ISSUE TITLE
how to run ctest in bmi-example-fortran?

### ISSUE THREAD

**Issue by teuben** [csdms/bmi#70]
The readme file refers to ctest how to run units tests and examples, but I'm not familiar how to run this. perhaps the commandline how to run this would be useful in this readme file.
I did learn something new:   ctest is something that comes with cmake

**Comment by teuben** [comment]
I may have answered this myself:     "make test" or "ctest" runs in the _build directory. I was in the wrong (main) directory, had to be in _build.

**Comment by mcflugen** [comment]
@teuben Yes, that's correct, *ctest* needs to be run in the *_build* directory. I made the same mistake when I recently went over this. We should update the docs to clarify.

**Comment by mdpiper** [comment]
Hi @teuben -- in the PRs listed above, I've updated the READMEs in the bmi-example-fortran, bmi-example-c, and bmi-example-cxx repos to try to clarify how to run ctest. Please let me know what you think. If they address this issue satisfactorily, I'll close the issue and merge the PRs.

**Comment by teuben** [comment]
they all work for me now, thanks for the clarifications and README updates.
